#!/bin/bash
# 18 · The two alerts that never turn off
#
# Run INSIDE the VM:   bash 18-avisos-que-no-se-apagan.sh
#
# SYMPTOM A — "Update System" reappears on every boot even if everything is up to date.
#   omarchy-provision-first-run only marks first-run as done if NO step
#   fails. Here enable-user-units.sh always failed, for TWO reasons:
#     1. The six .service files were never installed in /usr/lib/systemd/user/.
#        Upstream distributes them with the omarchy-settings package, which does not exist for
#        ARM (docs/file-layout.md: "systemd/user/*.service → /usr/lib/systemd/user/").
#     2. Those .service files invoke /usr/bin/omarchy-*, and this image had the
#        comandos en /usr/local/bin.
#   Since it was not marked, first-run repeats on every login and wifi.sh relaunches the alert.
#
# SYMPTOM B — "Linux kernel has been updated. Reboot?" always appears.
#   omarchy-update-restart looks for a vmlinuz inside /usr/lib/modules/<ver>/
#   that belongs to a package. On Arch x86_64 it is installed by the linux package; on
#   Arch Linux ARM, linux-aarch64 leaves the image in /boot/Image and does not create that
#   vmlinuz. The loop finds nothing, kernel_updated remains true and requests
#   a reboot on every update. Rebooting does not help: the condition cannot
#   volverse falsa.
set -uo pipefail
echo "==> A. comandos de omarchy a /usr/bin (donde los espera el árbol)"
n=0
for f in /usr/share/omarchy/bin/*; do
  [ -f "$f" ] || continue
  sudo ln -sfn "$f" "/usr/bin/$(basename "$f")" && n=$((n+1))
done
echo "   $n comandos enlazados en /usr/bin"

echo "==> A2. unidades de usuario donde systemd las busca"
# This was the missing step: without the .service files installed, enable-user-units.sh
# cannot work no matter how many paths are fixed.
if [ -d /usr/share/omarchy/default/systemd/user ]; then
  sudo install -d /usr/lib/systemd/user
  sudo cp -a /usr/share/omarchy/default/systemd/user/. /usr/lib/systemd/user/
  echo "   $(ls /usr/lib/systemd/user/*.service 2>/dev/null | wc -l) unidades disponibles"
else
  echo "   no encuentro /usr/share/omarchy/default/systemd/user"
fi

echo "==> B. envoltorio para el aviso de kernel"
sudo install -Dm755 /dev/stdin /usr/local/bin/omarchy-update-restart <<'KRN'
#!/bin/bash
if [ -z "${OMARCHY_SKIP_KERNEL_CHECK:-}" ]; then
  # modules.dep is generated by depmod and does not belong to any package. modules.builtin
  # is provided by linux-aarch64, so it serves to determine if the running kernel's
  # module directory is the one from the installed package.
  pkg=$(pacman -Qoq /usr/lib/modules/"$(uname -r)"/modules.builtin 2>/dev/null \
        || pacman -Qoq /usr/lib/modules/"$(uname -r)"/modules.order 2>/dev/null || true)
  [ -n "$pkg" ] && export OMARCHY_KERNEL_CURRENT=1
fi
REAL=/usr/bin/omarchy-update-restart
[ -x "$REAL" ] || exit 0
if [ -n "${OMARCHY_KERNEL_CURRENT:-}" ]; then
  sed 's#^kernel_updated=true$#kernel_updated=false#' "$REAL" | bash -s -- "$@"
else
  exec "$REAL" "$@"
fi
KRN
echo "   /usr/local/bin/omarchy-update-restart"

echo "==> C. completar first-run para que deje de repetirse"
bash /usr/share/omarchy/install/user/first-run/enable-user-units.sh \
  && echo "   enable-user-units.sh: ahora sí" \
  || echo "   sigue fallando: mira 'systemctl --user status' de las seis unidades"
omarchy-provision-first-run --force 2>&1 | tail -3

echo "==> comprobación"
printf "   unidades instaladas: %s\n" "$(ls /usr/lib/systemd/user/*.service 2>/dev/null | wc -l)"
printf "   first-run marcado:  %s\n" "$(omarchy-done check first-run-user && echo sí || echo NO)"
printf "   kernel en ejecución: %s\n" "$(uname -r)"
printf "   lo posee:            %s\n" "$(pacman -Qoq /usr/lib/modules/"$(uname -r)"/modules.builtin 2>/dev/null || echo "(nadie)")"
echo "   omarchy-update-restart no debería pedir reinicio a partir de ahora."
